server:
  port: 8080
#  ssl:
#    key-store: classpath:tomcat.keystore
#    key-password: 123456
#    key-alias: tomcat
#    key-store-type: JKS


spring:
  datasource:
    url: jdbc:mysql://8.140.113.169:3306/mongolian?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 123456
    #password: 522653
    driver-class-name: com.mysql.jdbc.Driver

#mybatis
mybatis:
  type-aliases-package: com.school.mogolian.po
#转化为驼峰命名
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000



