server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: 522653
    driver-class-name: com.mysql.jdbc.Driver


