server:
  port: 8080
#  ssl:
#    key-store: classpath:server.keystore
#    key-password: 12345678
#    key-alias: server_cert
#    key-store-type: JKS
#    enabled: true


spring:
  datasource:
    url: jdbc:mysql://8.140.113.169:3306/mongolian?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&useSSL=false
    username: root
    password: yb522653
    #password: 522653
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      #连接池名
      pool-name: DateHikariCP
      #最小空闲连接数
      minimum-idle: 10
      # 空闲连接存活最大时间，默认600000（10分钟）
      idle-timeout: 180000
      # 连接池最大连接数，默认是10
      maximum-pool-size: 60
      # 此属性控制从池返回的连接的默认自动提交行为,默认值：true
      auto-commit: true
      # 此属性控制池中连接的最长生命周期，值0表示无限生命周期，默认1800000即30分钟
      max-lifetime: 1800000
      # 数据库连接超时时间,默认30秒，即30000
      connection-timeout: 30000
      connection-test-query: SELECT 1


  redis:
    host: 8.140.113.169
    port: 6379
    database: 0

#mybatis
mybatis:
  type-aliases-package: com.school.mogolian.po
#转化为驼峰命名
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 3000
  mapper-locations: com/school/mongolian/dao/*.xml

fdfs:
  so-timeout: 1501  # 读取超时时间
  connect-timeout: 601  # 连接超时时间
  thumb-image:  # 缩略图配置
    width: 60
    height: 60
  tracker-list: 8.140.113.169:22122





